### DISCUSSION TITLE
Is it possible to use a different set of vector tiles (or limit the memory for creating the vector tiles)?

### DISCUSSION THREAD

**Discussion by 5balls** [motis-project/motis#587] [Q&A] [answered]
Hello!

First of all thanks a lot for you software - this is the first time I managed to run a software for public transport routing on a big gtfs file on my not so beefy vserver (16GB RAM) and I have tried quite some software. Critical seems to be the RAM needed for building the graphs (not necessarily the routing later) and with disabling the building of the vector tiles I could run the web interface and successfully routed on the DELFI gtfs file for germany (https://www.opendata-oepnv.de). I used the pbf extract of germany from geofabrik. Creating the tiles however makes me run out of memory. Is it possible to reduce the RAM usage? Possible at the expense of speed / hard disk usage during the creation of the graphs? I assume serving the tiles will use much less memory?

Now I have successfully converted the same pbf file to an "mbfiles" vector tile file with tilemaker and I can run the demo server for tilemaker as well and it seems to work well. Could this file be used with motis as well or are there differences in the creation of the vector tiles? This also in the mapbox format and mapbox gl is used for displaying it although maplibre gl should work as well I guess? I guess it is not really needed, because I will try to use the API endpoints in the end and can use a different map for my use case, but having one software would be really nice of course.

Sorry if this are basic questions, I'm quite new to a lot of this.

Thanks again and cheers,
Florian

**Comment by 5balls** [comment]
Hmm, the latest beta 3 of 2.0 could create the tiles - which doesn't answer the question but helps me currently.

Used config (which did not work for beta 2) was


```

server:
  port: 8080
  web_folder: ui
osm: /home/geo/data/de.osm.pbf
timetable:
  datasets:
    de:
      path: /home/geo/data/de.opendata-oepnv.gtfs.zip
street_routing: true
geocoding: true
osr_footpath: true
tiles:
  profile: tiles-profiles/full.lua
  flush_threshold: 100000
  db_size: 268435456
```
