### DISCUSSION TITLE
How to add coastline data to the tile server included in motis?

### DISCUSSION THREAD

**Discussion by 5balls** [motis-project/motis#631] [Q&A] [answered]
Hello again!
I'm quite happy to be able to host the planet file after tweaking some settings on my vserver. Thanks again for your great software, it is amazing!
I would like to show coastlines as well now as in the example given here: https://github.com/motis-project/tiles
Is there a corresponding setting in the yaml file for setting the coastline file? Will changing this setting render all the tiles from the pbf again?
Thanks a lot,
Florian

**Comment by felixguendling** [comment, marked as answer]
Yes, it's `tiles.coastline`.

```yaml
tiles:
  profile: tiles-profiles/profile.lua
  coastline: land-polygons-complete-4326.zip
```

Yes, changing this setting will render all tiles again if you run `motis import`.

Sorry, the docs are not up-to-date.
