### DISCUSSION TITLE
Getting 404 when querying reverseGeocoding api

### DISCUSSION THREAD

**Discussion by luckyhandler** [motis-project/motis#727] [Q&A] [answered]
I'm using motis 2.0.15 self-hosted.
I generated the API code for Dart with an openapi generator according to the `openapi.yaml`.

When I try to request this API with my own instance of motis I receive an `404` response .
When I replace the base url with `https://europe.motis-project.de/` I receive a response (for some unrelated Italian places and stops - see response in logs at the bottom)

There is no documentation on how motis needs to be configured via the config.yaml any more except [this](https://github.com/motis-project/motis/blob/master/docs/setup.md) one or do I miss a detailed documentation here?

As there's a difference in using `my own base url` and `https://europe.motis-project.de/` I would guess that it is a configuration issue of the config file. Does anyone spot the issue?

```yaml
server:
  port: 8080
  web_folder: ui
osm: ./osm.pbf
tiles:
  profile: tiles-profiles/full.lua
  db_size: 1099511627776
  flush_threshold: 10000000
timetable:
  first_day: TODAY
  num_days: 365
  railviz: true
  with_shapes: true
  ignore_errors: false
  adjust_footpaths: true
  merge_dupes_intra_src: false
  merge_dupes_inter_src: false
  link_stop_distance: 100
  update_interval: 60
  http_timeout: 10
  incremental_rt_update: false
  use_osm_stop_coordinates: false
  extend_missing_footpaths: true
  max_footpath_length: 25
  datasets:
    schedule-de-nv:
      path: ./schedule_germany-nv.zip
      default_bikes_allowed: false
    schedule-de-rv:
      path: ./schedule_germany-rv.zip
      default_bikes_allowed: false
    schedule-vgn:
      path: ./schedule_vgn.zip
      default_bikes_allowed: false
street_routing: true
osr_footpath: true
geocoding: false
reverse_geocoding: true
```

The log for requesting my own instance looks like this:

```
*** DioException ***:
uri: https://<my own base url>/api/v1/reverse-geocode?place=49.598119%252C11.003645%252C0
DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

uri: https://<my own base url>/api/v1/reverse-geocode?place=49.598119%252C11.003645%252C0
statusCode: 404
headers:
Response Text:
null
```

The log for requesting the demo motis instance looks like this:

```
uri: https://europe.motis-project.de/api/v1/reverse-geocode?place=49.598119%252C11.003645%252C0
statusCode: 200
headers:
 content-type: application/json
Response Text:
[{type: STOP, tokens: [], name: START, id: START, lat: 0, lon: 0, level: 0, areas: [], score: -10}, {type: STOP, tokens: [], name: END, id: END, lat: 0, lon: 0, level: 0, areas: [], score: -10}, {type: STOP, tokens: [], name: VIA0, id: VIA0, lat: 0, lon: 0, level: 0, areas: [], score: -10}, {type: STOP, tokens: [], name: VIA1, id: VIA1, lat: 0, lon: 0, level: 0, areas: [], score: -10}, {type: STOP, tokens: [], name: VIA2, id: VIA2, lat: 0, lon: 0, level: 0, areas: [], score: -10}, {type: STOP, tokens: [], name: VIA3, id: VIA3, lat: 0, lon: 0, level: 0, areas: [], score: -10}, {type: STOP, tokens: [], name: VIA4, id: VIA4, lat: 0, lon: 0, level: 0, areas: [], score: -10}, {type: STOP, tokens: [], name: VIA5, id: VIA5, lat: 0, lon: 0, level: 0, areas: [], score: -10}, {type: STOP, tokens: [], name: VIA6, id: VIA6, lat: 0, lon: 0, level: 0, areas: [], score: -10}, {type: PLACE, tokens: [], name: Monte Piselli - San Giacomo, id: node/1, lat: 0, lon: 0, areas: [{name: Italia, adminLevel: 2, matched: false, default: false}, {name: Abruzzo, adminLevel: 4, matched: false, default: false}, {name: Teramo, adminLevel: 6, matched: false, default: false}, {name: Valle Castellana, adminLevel: 8, matched: false, default: true}], score: 0}]
```

@felixguendling any idea?
