### ISSUE TITLE
target not found: /lookup/geo_station when trying to route with custom gtfs feed

### ISSUE THREAD

**Issue by Wissotsky** [motis-project/motis#425]
Tried routing with the gtfs feed of israel [israel-public-transportation.zip](https://gtfs.mot.gov.il/gtfsfiles/israel-public-transportation.zip)

On the frontend it just shows `Modul nicht geladen` when trying to find a path between two points(I tried all sorts of location/time combinations)

Config file:
```ini
modules=intermodal
modules=address
modules=tiles
modules=osrm
modules=ppr
modules=nigiri
modules=schedule

intermodal.router=nigiri
server.static_path=motis/web
dataset.begin=20240107
dataset.no_schedule=true

[import]
paths=schedule-israel:input/israel-public-transportation.zip
paths=osm:input/israel-and-palestine-latest.osm.pbf

[osrm]
profiles=motis/osrm-profiles/car.lua
profiles=motis/osrm-profiles/bike.lua
profiles=motis/osrm-profiles/bus.lua

[ppr]
profile=motis/ppr-profiles/default.json

[tiles]
profile=motis/tiles-profiles/background.lua
```

Terminal log:
```log
Used Options:

  server.host: 0.0.0.0
  server.port: 8080
  server.cert_path: ::dev::
  server.priv_key_path: ::dev::
  server.dh_path: ::dev::
  server.api_key:
  server.log_path:
  server.static_path: motis/web


  import.paths: schedule-israel:input/israel-public-transportation.zip, osm:input/israel-and-palestine-latest.osm.pbf
  import.data_dir: data
  import.require_successful: 1


  dataset.path:
  dataset.no_schedule: 1
  dataset.prefix:
  dataset.graph_path: default
  dataset.write_serialized: 1
  dataset.write_graph: 0
  dataset.read_graph: 0
  dataset.read_graph_mmap: 0
  dataset.cache_graph: 0
  dataset.apply_rules: 1
  dataset.adjust_footpaths: 1
  dataset.expand_footpaths: 1
  dataset.use_platforms: 0
  dataset.begin: 20240107
  dataset.num_days: 2
  dataset.planned_transfer_delta: 30
  dataset.wzr_classes_path:
  dataset.wzr_matrix_path:
  dataset.no_local_transport: 0
  dataset.debug_broken_trips: 0
  dataset.link_stop_distance: 100


  modules: intermodal, address, tiles, osrm, ppr, nigiri, schedule
  exclude_modules:


  remotes:


  mode: server
  batch_input_file: queries.txt
  batch_output_file: responses.txt
  init:
  num_threads: 4
  direct: 0


  csa.bridge: 0
  csa.expand_footpaths: 0


  gbfs.update_interval: 5
  gbfs.urls:
  gbfs.db_size: 1099511627776


  intermodal.router: nigiri
  intermodal.revise: 0


  nigiri.no_cache: 0
  nigiri.first_day:
  nigiri.num_days: 2
  nigiri.geo_lookup: 0
  nigiri.link_stop_distance: 100
  nigiri.default_timezone:
  nigiri.gtfsrt:


  osrm.profiles: motis/osrm-profiles/car.lua, motis/osrm-profiles/bike.lua, motis/osrm-profiles/bus.lua


  parking.db_max_size: 549755813888
  parking.max_walk_duration: 10
  parking.import.edge_rtree_max_size: 3221225472
  parking.import.area_rtree_max_size: 1073741824
  parking.import.lock_rtrees: 0
  parking.import_osm: 1
  parking.ppr_exact: 1
  parking.parkendd_endpoints:
  parking.parkendd_update_interval: 300


  path.use_cache:
  path.max_size: 34359738368


  paxforecast.forecast_results:
  paxforecast.behavior_stats:
  paxforecast.routing_cache:
  paxforecast.calc_load_forecast: 1
  paxforecast.publish_load_forecast: 0
  paxforecast.stats:
  paxforecast.deterministic_mode: 0
  paxforecast.min_delay_improvement: 5
  paxforecast.revert_forecasts: 0
  paxforecast.probability_threshold: 0.01
  paxforecast.allow_start_metas: 0
  paxforecast.allow_destination_metas: 0


  paxmon.journey_timezone:
  paxmon.journey_match_log:
  paxmon.match_tolerance: 0
  paxmon.split_groups: 0
  paxmon.split_groups_mean: 1.5
  paxmon.split_groups_stddev: 3
  paxmon.split_groups_seed: 0
  paxmon.max_station_wait_time: 0
  paxmon.generated_capacity_file:
  paxmon.stats:
  paxmon.capacity_match_log:
  paxmon.over_capacity_report:
  paxmon.broken_report:
  paxmon.reroute_unmatched: 0
  paxmon.reroute_file:
  paxmon.reroute_router: /tripbased
  paxmon.start_time: 1970-01-01T00:00:00Z+0200
  paxmon.end_time: 1970-01-01T00:00:00Z+0200
  paxmon.time_step: 60
  paxmon.arrival_delay_threshold: 20
  paxmon.preparation_time: 15
  paxmon.check_graph_times: 0
  paxmon.check_graph_integrity: 0
  paxmon.mcfp_scenario_dir:
  paxmon.mcfp_scenario_min_broken_groups: 500
  paxmon.mcfp_scenario_include_trip_info: 0
  paxmon.graph_log: 0
  paxmon.capacity_fuzzy_match_max_time_diff: 60
  paxmon.min_capacity: 0


  ppr.import.use_dem: 0
  ppr.profile: motis/ppr-profiles/default.json
  ppr.edge_rtree_max_size: 3221225472
  ppr.area_rtree_max_size: 1073741824
  ppr.lock_rtrees: 0
  ppr.prefetch_rtrees: 1
  ppr.verify_graph: 0
  ppr.check_integrity: 1


  railviz.initial_permalink:
  railviz.tiles_redirect:


  ris.db: ris.mdb
  ris.input:
  ris.db_max_size: 549755813888
  ris.init_time: 1970-01-01T00:00:00Z+0200
  ris.clear_db: 0
  ris.init_purge: 0ms
  ris.instant_forward: 0
  ris.gtfsrt.is_addition_skip_allowed: 1
  ris.http_proxy:
  ris.gtfsrt.update_interval: 60
  ris.rabbitmq1.name: rabbitmq1
  ris.rabbitmq1.host:
  ris.rabbitmq1.port: 0
  ris.rabbitmq1.username:
  ris.rabbitmq1.password:
  ris.rabbitmq1.vhost: ribasis
  ris.rabbitmq1.queue:
  ris.rabbitmq1.ca:
  ris.rabbitmq1.cert:
  ris.rabbitmq1.key:
  ris.rabbitmq1.prefetch_count: 0
  ris.rabbitmq1.stream_offset:
  ris.rabbitmq1.resume_stream: 1
  ris.rabbitmq1.max_resume_age: 0ms
  ris.rabbitmq1.update_interval: 60
  ris.rabbitmq2.name: rabbitmq2
  ris.rabbitmq2.host:
  ris.rabbitmq2.port: 0
  ris.rabbitmq2.username:
  ris.rabbitmq2.password:
  ris.rabbitmq2.vhost: ribasis
  ris.rabbitmq2.queue:
  ris.rabbitmq2.ca:
  ris.rabbitmq2.cert:
  ris.rabbitmq2.key:
  ris.rabbitmq2.prefetch_count: 0
  ris.rabbitmq2.stream_offset:
  ris.rabbitmq2.resume_stream: 1
  ris.rabbitmq2.max_resume_age: 0ms
  ris.rabbitmq2.update_interval: 60


  rt.validate_graph: 0
  rt.validate_constant_graph: 0
  rt.print_stats: 1
  rt.history: 0


  tiles.profile: motis/tiles-profiles/background.lua
  tiles.import.use_coastline: 0
  tiles.import.flush_threshold: 10000000
  tiles.db_size: 1099511627776


  tripbased.use_data_file: 1


     address: FINISHED
      nigiri: FINISHED
   osrm-bike: FINISHED
    osrm-bus: FINISHED
    osrm-car: FINISHED
         ppr: FINISHED
       tiles: FINISHED
[info][2024-01-06T07:09:19Z+0200][D:\a\motis\motis\base\core\src\logging.cc:23] [loading OSRM dataset: car] starting
[info][2024-01-06T07:09:19Z+0200][D:\a\motis\motis\base\core\src\logging.cc:23] [loading OSRM dataset: bus] starting
[info][2024-01-06T07:09:19Z+0200][D:\a\motis\motis\base\core\src\logging.cc:23] [loading OSRM dataset: bike] starting
[info][2024-01-06T07:09:20Z+0200][D:\a\motis\motis\base\core\src\logging.cc:30] [loading OSRM dataset: car] finished (1557.48ms)
[info][2024-01-06T07:09:20Z+0200][D:\a\motis\motis\base\core\src\logging.cc:30] [loading OSRM dataset: bus] finished (1579.59ms)
[info][2024-01-06T07:09:21Z+0200][D:\a\motis\motis\base\core\src\logging.cc:30] [loading OSRM dataset: bike] finished (2531.93ms)
Serving static files from C:\Users\Wissotsky\Desktop\camcompute\julia-navigator\somethingsomething\motis\web
[info][2024-01-06T07:09:21Z+0200][D:\a\motis\motis\base\launcher\src\main.cc:187] system boot finished
[warn][2024-01-06T07:10:39Z+0200][D:\a\motis\motis\base\module\src\dispatcher.cc:121] target not found: /railviz/get_trains
[warn][2024-01-06T07:10:52Z+0200][D:\a\motis\motis\base\module\src\dispatcher.cc:121] target not found: /lookup/geo_station
[warn][2024-01-06T07:10:52Z+0200][D:\a\motis\motis\base\module\src\dispatcher.cc:121] target not found: /lookup/geo_station
```

**Comment by felixguendling** [comment]
:wave: Thank you for giving MOTIS a try! :smile: 

Which MOTIS version are you using? It looks like it's a version where `nigiri` didn't provide `/lookup/geo_station` functionality yet. The latest release should not show more nigiri options `nigiri.railviz`, `nigiri.lookup`, etc. in the printed configuration.

Other than that, I would recommend to turn off the OSRM bus profile in the configuration and set `nigiri.first_day=20240107`. Since the old data model is not loaded anyway, you can remove `dataset.begin=20240107`.

**Comment by Wissotsky** [comment]
Yeah version was 0.10.1(Because I copypasted from the wiki installation example)

After updating and setting the tags it still doesnt work but now seems to have everything set to beginning of unix time(Jan 1 1970)
It doesnt add any new warnings/errors but the frontend does say now

```
Zeitraum nicht im Fahrplan
Auskunft von 1.1.1970 bis 2.1.1970 möglich
```
I have tried deleting the data folder and restarting

Log snippet at start
```
  paxmon.journey_timezone:
  paxmon.journey_match_log:
  paxmon.match_tolerance: 0
  paxmon.split_groups: 0
  paxmon.split_groups_mean: 1.5
  paxmon.split_groups_stddev: 3
  paxmon.split_groups_seed: 0
  paxmon.max_station_wait_time: 0
  paxmon.generated_capacity_file:
  paxmon.stats:
  paxmon.capacity_match_log:
  paxmon.over_capacity_report:
  paxmon.broken_report:
  paxmon.reroute_unmatched: 0
  paxmon.reroute_router: /tripbased
  paxmon.start_time: 1970-01-01T00:00:00Z+0200
  paxmon.end_time: 1970-01-01T00:00:00Z+0200
  paxmon.time_step: 60
  paxmon.arrival_delay_threshold: 20
  paxmon.preparation_time: 15
  paxmon.early_departure_tolerance: 0
  paxmon.check_graph_times: 0
  paxmon.check_graph_integrity: 0
  paxmon.mcfp_scenario_dir:
  paxmon.mcfp_scenario_min_broken_groups: 500
  paxmon.mcfp_scenario_include_trip_info: 0
  paxmon.graph_log: 0
  paxmon.capacity_fuzzy_match_max_time_diff: 60
  paxmon.min_capacity: 0


  ppr.import.use_dem: 0
  ppr.profile: motis/ppr-profiles/default.json
  ppr.edge_rtree_max_size: 3221225472
  ppr.area_rtree_max_size: 1073741824
  ppr.lock_rtrees: 0
  ppr.prefetch_rtrees: 1
  ppr.verify_graph: 0
  ppr.check_integrity: 1


  railviz.initial_permalink:
  railviz.tiles_redirect:


  ris.db: ris.mdb
  ris.input:
  ris.db_max_size: 549755813888
  ris.init_time: 1970-01-01T00:00:00Z+0200
  ris.delayed_init: 0
  ris.clear_db: 0
  ris.init_purge: 0ms
  ris.instant_forward: 0
  ris.gtfsrt.is_addition_skip_allowed: 1
  ris.http_proxy: 
  ris.gtfsrt.update_interval: 60
  ris.ribasis_fahrt.name: ribasis_fahrt
  ris.ribasis_fahrt.host:
  ris.ribasis_fahrt.port: 0
  ris.ribasis_fahrt.username:
  ris.ribasis_fahrt.password:
  ris.ribasis_fahrt.vhost: ribasis
  ris.ribasis_fahrt.queue:
  ris.ribasis_fahrt.ca:
  ris.ribasis_fahrt.cert:
  ris.ribasis_fahrt.key:
  ris.ribasis_fahrt.prefetch_count: 0
  ris.ribasis_fahrt.stream_offset:
  ris.ribasis_fahrt.resume_stream: 1
  ris.ribasis_fahrt.max_resume_age: 0ms
  ris.ribasis_fahrt.update_interval: 60
  ris.ribasis_formation.name: ribasis_formation
  ris.ribasis_formation.host:
  ris.ribasis_formation.port: 0
  ris.ribasis_formation.username:
  ris.ribasis_formation.password: 
  ris.ribasis_formation.vhost: ribasis
  ris.ribasis_formation.queue:
  ris.ribasis_formation.ca:
  ris.ribasis_formation.cert:
  ris.ribasis_formation.key:
  ris.ribasis_formation.prefetch_count: 0
  ris.ribasis_formation.stream_offset:
  ris.ribasis_formation.resume_stream: 1
  ris.ribasis_formation.max_resume_age: 0ms
  ris.ribasis_formation.update_interval: 60
```
