### ISSUE TITLE
OSR backend doesn't return a walking route

### ISSUE THREAD

**Issue by gbastkowski** [motis-project/motis#550]
MOTIS self-compiled from master, germany as OSM dataset:
```
{
        "destination": {
                "type": "Module",
                "target": "/osrm/via"
        },
        "content_type": "OSRMViaRouteRequest",
        "content": {
                "profile": "foot",
                "waypoints": [
                        {"lat": 52.6571386304404, "lng": 13.205059299889228},
                        {"lat": 52.666255891666715, "lng": 13.227007313289821}
                ]
        }
}
```

```
Used Options:

  server.host: 0.0.0.0
  server.port: 8080
  server.cert_path: ::dev::
  server.priv_key_path: ::dev::
  server.dh_path: ::dev::
  server.api_key: 
  server.log_path: 
  server.static_path: motis/web


  import.paths: schedule-gtfs-de:gtfs-de, osm:germany-latest.osm.pbf
  import.data_dir: data/
  import.require_successful: 1


  modules: address, intermodal, nigiri, osr, tiles
  exclude_modules: 


  remotes: 


  mode: server
  batch_input_file: queries.txt
  batch_output_file: responses.txt
  init: 
  num_threads: 28
  direct: 0
  otlp_http: 0


  gbfs.update_interval: 5
  gbfs.urls: 
  gbfs.db_size: 1099511627776


  intermodal.router: nigiri
  intermodal.revise: 0
  intermodal.timeout: 0


  nigiri.no_cache: 0
  nigiri.adjust_footpaths: 1
  nigiri.match_duplicates: 0
  nigiri.merge_dupes_intra_src: 0
  nigiri.merge_dupes_inter_src: 0
  nigiri.max_footpath_length: 65535
  nigiri.first_day: TODAY
  nigiri.num_days: 93
  nigiri.lookup: 1
  nigiri.guesser: 1
  nigiri.railviz: 1
  nigiri.routing: 1
  nigiri.link_stop_distance: 100
  nigiri.default_timezone: Europe/Berlin
  nigiri.gtfsrt: 
  nigiri.gtfsrt_paths: 
  nigiri.gtfsrt_incremental: 0
  nigiri.debug: 0
  nigiri.bikes_allowed_default: 0


  osr.lock: 1


  osrm.profiles: motis/osrm-profiles/bike.lua, motis/osrm-profiles/bus.lua, motis/osrm-profiles/car.lua, motis/osrm-profiles/foot.lua


  parking.db_max_size: 549755813888
  parking.max_walk_duration: 10
  parking.import.edge_rtree_max_size: 3221225472
  parking.import.area_rtree_max_size: 1073741824
  parking.import.lock_rtrees: 0
  parking.import_osm: 1
  parking.ppr_exact: 1
  parking.parkendd_endpoints: 
  parking.parkendd_update_interval: 300


  ppr.import.use_dem: 0
  ppr.profile: motis/ppr-profiles/default.json
  ppr.edge_rtree_max_size: 3221225472
  ppr.area_rtree_max_size: 1073741824
  ppr.lock_rtrees: 0
  ppr.prefetch_rtrees: 1
  ppr.verify_graph: 0
  ppr.check_integrity: 1


  tiles.profile: motis/tiles-profiles/background.lua
  tiles.import.use_coastline: 0
  tiles.import.flush_threshold: 10000000
  tiles.db_size: 1099511627776
```
