### ISSUE TITLE
motis import (tt) stuck at 37% (parse shapes)

### ISSUE THREAD

**Issue by SebastiaanWouters** [motis-project/motis#618]
When running the following script, the tt part of the motis command is stuck at 37% (Parse Shapes) 

```
#!/usr/bin/env bash
TARGET="linux-amd64"
wget https://github.com/motis-project/motis/releases/download/v2.0.0-beta.5/motis-linux-amd64.tar.bz2
rm -rf motis/*
mkdir -p motis
mkdir -p motis/input
tar xf motis-${TARGET}.tar.bz2 -C motis
rm -rf motis-${TARGET}.tar.bz2
wget https://download.geofabrik.de/europe/belgium-latest.osm.pbf -O ./motis/input/belgium-latest.osm.pbf
wget https://gtfs.irail.be/de-lijn/de_lijn-gtfs.zip -O ./motis/input/gtfs.zip
cd motis
./motis ./input/belgium-latest.osm.pbf ./input/gtfs.zip
```

![image](https://github.com/user-attachments/assets/0e857859-511b-4843-9cc3-a5b57179917e)

**Comment by felixguendling** [comment]
Thanks for your report! We assumed that the `shapes.txt` file is sorted. For random order the performance is very bad.

The performance issue should can be fixed. I tried using another data structure here:
https://github.com/motis-project/nigiri/pull/149

But as you can see in the issue, the shapes of `de_lijn-gtfs.zip` look very strange. We need to investigate if that's an issue with the shapes data or not.

--------------------

For now, you can try using MOTIS v2 beta without shapes:

Create a `config.yml` file:

```yaml
osm: belgium-latest.osm.pbf
timetable:
  with_shapes: false
  datasets:
    be:
      path: de_lijn-gtfs.zip
tiles:
  profile: tiles-profiles/full.lua
geocoding: true
street_routing: true
```

- Run `./motis import`. This will create the `./data` folder.
- Then run `./motis server`
