### ISSUE TITLE
GBFS geojson parser error

### ISSUE THREAD

**Issue by felixguendling** [motis-project/motis#632]
![image](https://github.com/user-attachments/assets/1d5ed12a-99e2-48fa-bc52-ab35d2b5e7d7)

Is this expected @pablohoch ?

**Comment by felixguendling** [comment]
```
osm: germany-latest.osm.pbf
tiles:
  profile: tiles-profiles/full.lua
  db_size: 274877906944
  flush_threshold: 100000
timetable:
  first_day: TODAY
  num_days: 365
  railviz: true
  with_shapes: true
  ignore_errors: false
  adjust_footpaths: true
  merge_dupes_intra_src: false
  merge_dupes_inter_src: false
  link_stop_distance: 100
  update_interval: 60
  http_timeout: 10
  incremental_rt_update: false
  max_footpath_length: 15
  datasets:
    deDELFI.gtfs:
      path: de_DELFI.gtfs.zip
      default_bikes_allowed: false
street_routing: true
osr_footpath: false
elevators: false
geocoding: true
reverse_geocoding: false
gbfs:
  feeds:
    mobidata:
      url: https://api.mobidata-bw.de/sharing/gbfs/v3/manifest.json
```
