### ISSUE TITLE
bug: (or error in GTFS ?) "timezone not set"

### ISSUE THREAD

**Issue by nicolaswurtz** [motis-project/motis#677]
Motis version: beta22

Hi!

I encounter a strange error with [this gtfs file](https://www.data.gouv.fr/fr/datasets/r/30d942c2-cff8-4440-a7b2-f72de4e8c3c6): Motis importation failed with "timezone not set".

GTFS file seems to be valid (cf https://transport.data.gouv.fr/validation/307101?token=c026025f-5502-4e5b-92e7-29ef2d7a2a0c), I've manualy tried to check the presence of timezone in `agency.txt` or trying to add a `stop_timezone` column in `stops.txt` but nothing works.

If you've time to check why, it would be really helpful!

Thank you!

_PS: As I use a lot (~500) of GTFS files in my conf, it was pretty hard to find which one failed during importation, could it be possible to add the name of the file/dataset processed when failing in this error message too?_

My conf:

```yml
tt
  existing: {}
  current: {"nigiri_bin_ver":7,"timetable":4955646766484756824}
adr_extend
  existing: {}
  current: {"adr_bin_ver":4,"geocoding":1,"nigiri_bin_ver":7,"osm":14695981039346656037,"reverse_geocoding":0,"timetable":4955646766484756824}
  adr_extend: [■                                                       ]   0%
          tt: [■■■■■■■■■■■■■■■■                                        ]  27% | Parse Routes
unable to import: timezone not set
config:
server:
  host: 0.0.0.0
  port: 1280
  web_folder: ui
  n_threads: 8
timetable:
  first_day: TODAY
  num_days: 365
  railviz: true
  with_shapes: true
  ignore_errors: false
  adjust_footpaths: true
  merge_dupes_intra_src: false
  merge_dupes_inter_src: false
  link_stop_distance: 100
  update_interval: 60
  http_timeout: 10
  incremental_rt_update: false
  max_footpath_length: 15
  datasets:
    test:
      path: ./test.zip
      default_bikes_allowed: false
street_routing: false
osr_footpath: false
elevators: false
geocoding: true
reverse_geocoding: false
```

**Comment by felixguendling** [comment]
With `beta-23` it's possible to load the timetable without anything else. Here's the config with the default timezone set:

```
timetable:
  datasets:
    test:
      path: google-transit-23-09-24.zip
      default_timezone: Europe/Paris
```
