### ISSUE TITLE
Segmentation fault with motis v2.0.49 on motis server

### ISSUE THREAD

**Issue by thelleboid-tsr** [motis-project/motis#817]
With motis v2.0.49, when running `motis server` I get a segmentation fault:

❯ ../motis/motis server
Segmentation fault (core dumped)

## Environment
WSL2 on Ubuntu
```
❯ uname -r
5.15.167.4-microsoft-standard-WSL2
```

## Config file
```yaml
# OSM data comes from https://download.geofabrik.de/europe/france/reunion-latest.osm.pbf , it weights 32 MB
osm: ../reunion-2025-04-14.osm.pbf
tiles:
  profile: tiles-profiles/full.lua
  db_size: 274877906944
  flush_threshold: 100000
timetable:
  first_day: TODAY
  num_days: 365
  railviz: true
  with_shapes: true
  adjust_footpaths: true
  merge_dupes_intra_src: false
  merge_dupes_inter_src: false
  link_stop_distance: 100
  update_interval: 60
  http_timeout: 30
  incremental_rt_update: false
  use_osm_stop_coordinates: false
  extend_missing_footpaths: false
  max_footpath_length: 15
  max_matching_distance: 25
  datasets:
    car-jaune:
      path: ../car-jaune-2025-04-14.zip
      # Comes from https://pysae.com/api/v2/groups/car-jaune/gtfs/pub
      default_bikes_allowed: false
      rt:
        - url: https://pysae.com/api/v2/groups/car-jaune/gtfs-rt
street_routing: true
osr_footpath: false
geocoding: true
reverse_geocoding: true
```

It works with motis 2.0.43

Let me know if I can help you reproducing the error or find what could cause the issue.
