### ISSUE TITLE
GBFS: deer Carsharing provider is not picked up for intermodal routing.

### ISSUE THREAD

**Issue by 1Maxnet1** [motis-project/motis#844]
I wanted to try out which intermodal routing results MOTIS provides for carsharing integration, so I tried with a Baden-Württemberg wide GTFS dataset and OSM Dataset and the deer-Carsharing GBFS feed, which is part of the Mobidata-BW combined feed as well.

MOTIS-Version tested: 2.0.63

GTFS-Dataset source: https://www.nvbw.de/fileadmin/user_upload/service/open_data/fahrplandaten_mit_liniennetz/bwgesamt.zip

OSM dataset: from Geofabrik.de

config.yml:

```yml
server:
  port: 8080
  web_folder: ui
osm: baden-wuerttemberg-latest.osm.pbf
timetable:
  datasets:
    nvbw:
      path: bwgesamt.zip

gbfs:
  feeds:
    deer:
      url: https://api.mobidata-bw.de/sharing/gbfs/v2/deer/gbfs
tiles:
  profile: tiles-profiles/full.lua
street_routing: true
geocoding: true
osr_footpath: true
```

Log for `motis server`:
```
2025-05-07T14:12:03Z [info] [server.cc:162] [motis.server] listening on 0.0.0.0:8080
local link: http://localhost:8080
2025-05-07T14:12:03Z [info] [timer.cc:9] [scoped_timer] [gbfs::update] starting
2025-05-07T14:12:03Z [info] [timer.cc:9] [scoped_timer] [compute routing data for gbfs provider deer] starting
2025-05-07T14:12:05Z [info] [timer.cc:18] [scoped_timer] [compute routing data for gbfs provider deer] finished (2176.394ms)
2025-05-07T14:12:05Z [info] [timer.cc:18] [scoped_timer] [gbfs::update] finished (2319.997ms)
...
```

## Examples:
1. Routing from Vaihingen/Enz to Calw:

![Image](https://github.com/user-attachments/assets/ba645679-3694-441b-bca6-f3ddc78932af)

Comment: There is a station at a close by shopping center (with a car available when during testing), but the routing does not use it. Therefore it uses a car at the end of the routing for 1 minute. I expected it to be faster to rent a car in Vaihingen Enz and give it back at one of the many stations in Calw

2. Routing from Hochdorf/Enz Keltenmuseum to Stuttgart-Möhringen

![Image](https://github.com/user-attachments/assets/5c931677-0d76-4b80-b577-9a68b516835f)

Again I'd expect the pure sharing or the sharing + public-transport to show up, as both is faster compared to pure public-transport. One option would be to use the Carsharing to Schwieberdingen close by and continue with Bus from there. Or directly drive to the Carsharing station in Möhringen.
