### ISSUE TITLE
Wish: support for private feeds

### ISSUE THREAD

**Issue by markstos** [motis-project/motis#863]
For our use case, we have a number of customers in California. A number of them have public GTFS feeds, but several of have private GTFS feeds. For example, corporate shuttles only the employees to go to work, or a shuttle only to travel around within a particular campus.

Without support for these built into a routing engine, we rebuild several graphs for California: one with all the public feeds and then several additional ones that contain all the public feeds plus the one or two private feeds for each customer.

To support this use case, we are interested what might be called "Provate data sets".

## Configuration

The configuration would include a data model maybe like this:

```yaml
private_datasets:
    cust1:
        api_key: 'WE-CHOOSE'
        path: cust1.gtfs.zip
```

Or:

```yaml
# If a private_api_key is defined, it's private.
datasets:
    cust1:
        private_api_key: 'WE-CHOOSE'
        path: cust1.gtfs.zip
```

Some customers have more than one private feed. For example, they have two campuses. 

## Building private feeds

- Private feeds would have the `private_api_key` added to their metadata. 

## Serving Private feeds

- By default, routing ignores feeds marked as private.
- If an API key is provided, it's validated against the configuration, then routing considers those feeds plus all public feeds.

(We are not currently using Motis, but it seems to support the other features we need. Support for this might be the tipping point to switch).
